# Netflix Content Explorer

**Minor Project – Artificial Intelligence**

**Student Name:** Saad Salar Shaik  
**Course:** B.Tech CSE – AI and ML  
**Tools Used:** Python, Pandas, NumPy, Google Colab  

## Objective

This project analyzes the Netflix Titles dataset using Python. It cleans missing values and provides an interactive, menu-driven program to answer business-style questions about Netflix movies and TV shows.

## Dataset Description

The project uses the Netflix Titles dataset. It contains information about Netflix movies and TV shows, including title, type, director, cast, country, date added, release year, rating, and duration.

The dataset was loaded into a Pandas DataFrame for cleaning and analysis.

In [9]:
from google.colab import files

uploaded = files.upload()

Saving archive.zip to archive.zip

In [10]:
import zipfile
import os

zip_name = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall("/content/netflix_data")

print(os.listdir("/content/netflix_data"))

['netflix_titles.csv']

In [11]:
import os

for root, folders, files_in_folder in os.walk("/content/netflix_data"):
    for filename in files_in_folder:
        print(os.path.join(root, filename))

/content/netflix_data/netflix_titles.csv

In [12]:
import pandas as pd
import numpy as np

file_path = "/content/netflix_data/netflix_titles.csv"

df = pd.read_csv(file_path)

print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset shape: (8807, 12)

Column names:
['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [13]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

display(df.head())

Dataset shape: (8807, 12)

Column names:
['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

Data types:
show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

Missing values:
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

Duplicate rows:
0

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [41]:
# Make a copy so the original imported data remains unchanged
cleaned_df = df.copy()

# Fill missing text values
cleaned_df["country"] = cleaned_df["country"].fillna("Unknown")
cleaned_df["director"] = cleaned_df["director"].fillna("Not Listed")
cleaned_df["cast"] = cleaned_df["cast"].fillna("Not Listed")
cleaned_df["rating"] = cleaned_df["rating"].fillna("Not Rated")

# Remove rows where date_added is missing
cleaned_df = cleaned_df.dropna(subset=["date_added"]).copy()

# Convert date_added into a proper date
cleaned_df["date_added"] = pd.to_datetime(
    cleaned_df["date_added"],
    errors="coerce"
)

# Remove rows that could not be converted into dates
cleaned_df = cleaned_df.dropna(subset=["date_added"]).copy()

# Create year_added
cleaned_df["year_added"] = cleaned_df["date_added"].dt.year.astype(int)

print("Shape after cleaning:", cleaned_df.shape)
display(cleaned_df.head())

Shape after cleaning: (8709, 13)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Listed,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021
1,s2,TV Show,Blood & Water,Not Listed,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021
3,s4,TV Show,Jailbirds New Orleans,Not Listed,Not Listed,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021
4,s5,TV Show,Kota Factory,Not Listed,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021

In [15]:
print("Cleaned dataset shape:", cleaned_df.shape)

print("\nMissing values in important columns:")
print(
    cleaned_df[
        ["country", "director", "cast", "rating", "date_added", "year_added"]
    ].isnull().sum()
)

print("\nData types:")
print(cleaned_df[
    ["date_added", "release_year", "year_added"]
].dtypes)

print("\nYear added preview:")
display(cleaned_df[["date_added", "year_added"]].head())

Cleaned dataset shape: (8709, 13)

Missing values in important columns:
country       0
director      0
cast          0
rating        0
date_added    0
year_added    0
dtype: int64

Data types:
date_added      datetime64[ns]
release_year             int64
year_added               int64
dtype: object

Year added preview:

  date_added  year_added
0 2021-09-25        2021
1 2021-09-24        2021
2 2021-09-24        2021
3 2021-09-24        2021
4 2021-09-24        2021

## Data Cleaning

The dataset was cleaned by replacing missing country values with "Unknown", missing director and cast values with "Not Listed", and missing rating values with "Not Rated". Rows without a date-added value were removed. The date-added column was converted into a datetime format, and a new year-added column was created for yearly analysis.

In [16]:
print("Movies vs TV Shows")
print(cleaned_df["type"].value_counts())

print("\nTitles added each year")
print(cleaned_df["year_added"].value_counts().sort_index())

Movies vs TV Shows
type
Movie      6131
TV Show    2578
Name: count, dtype: int64

Titles added each year
year_added
2008       2
2009       2
2010       1
2011      13
2012       3
2013      10
2014      23
2015      73
2016     418
2017    1164
2018    1625
2019    1999
2020    1878
2021    1498
Name: count, dtype: int64

Beginning the tests of the functions

In [17]:
def show_content_type_counts():
    print("Count of Movies vs TV Shows")
    print(cleaned_df["type"].value_counts())


def show_titles_added_each_year():
    print("Number of titles added each year")
    yearly_counts = cleaned_df["year_added"].value_counts().sort_index()
    print(yearly_counts)
show_content_type_counts()
print()
show_titles_added_each_year()

Count of Movies vs TV Shows
type
Movie      6131
TV Show    2578
Name: count, dtype: int64

Number of titles added each year
year_added
2008       2
2009       2
2010       1
2011      13
2012       3
2013      10
2014      23
2015      73
2016     418
2017    1164
2018    1625
2019    1999
2020    1878
2021    1498
Name: count, dtype: int64

In [18]:
def show_top_10_countries():
    print("Top 10 Producing Countries")

    countries = cleaned_df["country"].str.split(",").explode()
    countries = countries.str.strip()

    top_countries = countries.value_counts().head(10)
    print(top_countries)


def show_top_5_genres():
    print("Top 5 Most Common Genres")

    genres = cleaned_df["listed_in"].str.split(",").explode()
    genres = genres.str.strip()

    top_genres = genres.value_counts().head(5)
    print(top_genres)
show_top_10_countries()

print()

show_top_5_genres()

Top 10 Producing Countries
country
United States     3643
India             1045
Unknown            827
United Kingdom     787
Canada             432
France             389
Japan              314
Spain              228
South Korea        226
Germany            225
Name: count, dtype: int64

Top 5 Most Common Genres
listed_in
International Movies      2752
Dramas                    2427
Comedies                  1674
International TV Shows    1328
Documentaries              869
Name: count, dtype: int64

In [23]:
def search_titles_by_keyword():
    keyword = input("Enter a keyword to search in titles: ").strip()

    if keyword == "":
        print("Please enter a non-empty keyword.")
        return

    matches = cleaned_df[
        cleaned_df["title"].str.contains(
            keyword,
            case=False,
            na=False
        )
    ]

    if matches.empty:
        print(f'No titles found containing "{keyword}".')
        return

    print(f'\nTitles containing "{keyword}":')
    print(f"Total matches: {len(matches)}")

    columns_to_show = [
        "show_id",
        "type",
        "title",
        "release_year",
        "rating",
        "country"
    ]

    display(matches[columns_to_show].head(20))

    if len(matches) > 20:
        print("Only the first 20 results are displayed.")

In [26]:
def show_rating_distribution():
    print("Rating Distribution")
    rating_counts = cleaned_df["rating"].value_counts()
    print(rating_counts)


def show_oldest_newest_release_year():
    print("Oldest and Newest Release Years")

    oldest_year = cleaned_df["release_year"].min()
    newest_year = cleaned_df["release_year"].max()

    print(f"\nOldest release year: {oldest_year}")
    print(f"Newest release year: {newest_year}")

    oldest_titles = cleaned_df[
        cleaned_df["release_year"] == oldest_year
    ][["title", "type", "release_year"]].head(10)

    newest_titles = cleaned_df[
        cleaned_df["release_year"] == newest_year
    ][["title", "type", "release_year"]].head(10)

    print("\nTitles from the oldest release year:")
    display(oldest_titles)

    print("\nTitles from the newest release year:")
    display(newest_titles)
show_rating_distribution()
show_oldest_newest_release_year()

Rating Distribution
rating
TV-MA        3183
TV-14        2133
TV-PG         838
R             799
PG-13         490
TV-Y7         330
TV-Y          300
PG            287
TV-G          212
NR             78
G              41
TV-Y7-FV        5
Not Rated       4
NC-17           3
UR              3
66 min          1
74 min          1
84 min          1
Name: count, dtype: int64
Oldest and Newest Release Years

Oldest release year: 1925
Newest release year: 2021

Titles from the oldest release year:

                                  title     type  release_year
4250  Pioneers: First Women Filmmakers*  TV Show          1925

Titles from the newest release year:

                                  title     type  release_year
1                         Blood & Water  TV Show          2021
2                             Ganglands  TV Show          2021
3                 Jailbirds New Orleans  TV Show          2021
4                          Kota Factory  TV Show          2021
5                         Midnight Mass  TV Show          2021
6      My Little Pony: A New Generation    Movie          2021
8         The Great British Baking Show  TV Show          2021
9                          The Starling    Movie          2021
10  Vendetta: Truth, Lies and The Mafia  TV Show          2021
11                     Bangkok Breaking  TV Show          2021

In [25]:
search_titles_by_keyword()

Enter a keyword to search in titles: love

Titles containing "love":
Total matches: 196

,show_id,type,title,release_year,rating,country
25,s26,TV Show,Love on the Spectrum,2021,TV-14,Australia
158,s159,Movie,Love Don't Cost a Thing,2003,PG-13,United States
159,s160,Movie,Love in a Puff,2010,TV-MA,Hong Kong
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",2010,TV-MA,India
227,s228,Movie,Really Love,2020,TV-MA,United States
246,s247,Movie,Man in Love,2021,TV-MA,Unknown
375,s376,Movie,Resort to Love,2021,TV-14,Unknown
402,s403,Movie,The Last Letter From Your Lover,2021,TV-MA,United Kingdom
485,s486,Movie,Lethal Love,2021,TV-14,Unknown
506,s507,Movie,This Little Love Of Mine,2021,TV-G,Australia
615,s616,Movie,Why Do Fools Fall in Love,1998,R,United States
656,s657,Movie,Love Is a Story,2015,TV-MA,Romania
659,s660,TV Show,Bangkok Love Stories: Innocence,2018,TV-14,Thailand
731,s732,TV Show,Love (ft. Marriage and Divorce),2021,TV-14,South Korea
755,s756,Movie,Kitty Love: An Homage to Cats,2021,TV-G,Netherlands
798,s799,Movie,Love Jones,1997,R,United States
849,s850,Movie,Sam Smith: Love Goes - Live at Abbey Road Studios,2020,TV-G,Unknown
875,s876,Movie,Love or Money,2020,TV-MA,Unknown
883,s884,TV Show,"Love, Death & Robots",2021,TV-MA,United States
922,s923,Movie,The Clovehitch Killer,2018,TV-MA,United States

Only the first 20 results are displayed.

In [28]:
def show_content_added_in_specific_year():
    year_input = input("Enter the year content was added: ").strip()

    if not year_input.isdigit():
        print("Please enter a valid year, such as 2020.")
        return

    year = int(year_input)

    matches = cleaned_df[cleaned_df["year_added"] == year]

    if matches.empty:
        print(f"No content was added in {year}.")
        return

    print(f"\nContent added in {year}:")
    print(f"Total titles: {len(matches)}")

    columns_to_show = [
        "show_id",
        "type",
        "title",
        "release_year",
        "rating",
        "country"
    ]

    display(matches[columns_to_show].head(30))

    if len(matches) > 30:
        print("Only the first 30 results are displayed.")

In [31]:
show_content_added_in_specific_year()

Enter the year content was added: 2020

Content added in 2020:
Total titles: 1878

,show_id,type,title,release_year,rating,country
1470,s1471,Movie,Alaska Is a Drag,2017,TV-MA,United States
1471,s1472,Movie,Best of Stand-Up 2020,2020,TV-MA,Unknown
1472,s1473,Movie,Bobby Jasoos,2014,TV-14,India
1473,s1474,TV Show,Chilling Adventures of Sabrina,2020,TV-14,United States
1474,s1475,Movie,Tarung Sarung,2020,TV-PG,Indonesia
1475,s1476,Movie,Too Handsome to Handle,2019,TV-14,Indonesia
1476,s1477,TV Show,Best Leftovers Ever!,2020,TV-G,United States
1477,s1478,TV Show,Dare Me,2019,TV-MA,United States
1478,s1479,TV Show,Equinox,2020,TV-MA,"Denmark, United States"
1479,s1480,TV Show,SanPa: Sins of the Savior,2020,TV-MA,Italy
1480,s1481,TV Show,Still Game,2018,TV-14,United Kingdom
1481,s1482,Movie,The Rope Curse 2,2020,TV-MA,Taiwan
1482,s1483,TV Show,Transformers: War for Cybertron: Earthrise,2020,TV-Y7,Unknown
1483,s1484,TV Show,A Love So Beautiful,2020,TV-PG,South Korea
1484,s1485,Movie,Cops and Robbers,2020,PG-13,United States
1485,s1486,Movie,Rango,2011,PG,"United States, Canada"
1486,s1487,Movie,Death to 2020,2020,TV-MA,United States
1487,s1488,TV Show,Sakho & Mangane,2019,TV-MA,Senegal
1488,s1489,Movie,DNA,2020,TV-MA,"France, Algeria"
1489,s1490,TV Show,Regiment Diaries,2020,TV-PG,India
1490,s1491,Movie,The Magic School Bus Rides Again In the Zone,2020,TV-Y,Canada
1491,s1492,Movie,AK vs AK,2020,TV-MA,India
1492,s1493,TV Show,Bridgerton,2020,TV-MA,United States
1493,s1494,Movie,Isa Pa with Feelings,2019,TV-G,Philippines
1494,s1495,Movie,We Can Be Heroes,2020,PG,United States
1495,s1496,Movie,Bridezilla,2019,TV-MA,Indonesia
1496,s1497,Movie,Cemara's Family,2018,TV-G,Indonesia
1497,s1498,Movie,"Hello, Love, Goodbye",2019,TV-14,Philippines
1498,s1499,Movie,The History of Future Folk,2012,TV-14,United States
1499,s1500,Movie,The Midnight Sky,2020,PG-13,United States

Only the first 30 results are displayed.

In [32]:
show_content_added_in_specific_year()

Enter the year content was added: hello
Please enter a valid year, such as 2020.

In [40]:
def show_total_unique_countries():
    print("Total Unique Countries")

    countries = cleaned_df["country"].str.split(",").explode()
    countries = countries.str.strip()

    unique_countries = countries.dropna().unique()

    print(f"Total unique countries: {len(unique_countries)}")


def show_release_year_statistics():
    print("Release Year Summary Statistics")

    release_years = cleaned_df["release_year"].dropna().to_numpy()

    print(f"Mean: {np.mean(release_years):.2f}")
    print(f"Median: {np.median(release_years):.2f}")
    print(f"Minimum: {np.min(release_years)}")
    print(f"Maximum: {np.max(release_years)}")
    print(f"Standard deviation: {np.std(release_years):.2f}")
    print(f"Variance: {np.var(release_years):.2f}")

show_total_unique_countries()

print()

show_release_year_statistics()

Total Unique Countries
Total unique countries: 124

Release Year Summary Statistics
Mean: 2014.20
Median: 2017.00
Minimum: 1925
Maximum: 2021
Standard deviation: 8.83
Variance: 77.89

## Interactive Menu

The menu-driven interface uses a `while True` loop to repeatedly display choices to the user. The program calls the appropriate function according to the selected option and exits safely when the user enters `0`.

Now, building a menu...

In [37]:
def show_menu():
    print("\n" + "=" * 50)
    print("        NETFLIX CONTENT EXPLORER")
    print("=" * 50)
    print("1. Count of Movies vs TV Shows")
    print("2. Number of titles added each year")
    print("3. Top 10 producing countries")
    print("4. Top 5 most common genres")
    print("5. Rating distribution")
    print("6. Oldest and newest release years")
    print("7. Search titles by keyword")
    print("8. Content added in a specific year")
    print("9. Total unique countries")
    print("10. Summary statistics on release year")
    print("0. Quit")
    print("=" * 50)


while True:
    show_menu()

    choice = input("Enter your choice (0-10): ").strip()

    if choice == "1":
        show_content_type_counts()

    elif choice == "2":
        show_titles_added_each_year()

    elif choice == "3":
        show_top_10_countries()

    elif choice == "4":
        show_top_5_genres()

    elif choice == "5":
        show_rating_distribution()

    elif choice == "6":
        show_oldest_newest_release_year()

    elif choice == "7":
        search_titles_by_keyword()

    elif choice == "8":
        show_content_added_in_specific_year()

    elif choice == "9":
        show_total_unique_countries()

    elif choice == "10":
        show_release_year_statistics()

    elif choice == "0":
        print("Thank you for using Netflix Content Explorer.")
        break

    else:
        print("Invalid choice. Please enter a number from 0 to 10.")

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 1
Count of Movies vs TV Shows
type
Movie      6131
TV Show    2578
Name: count, dtype: int64

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 2
Number of titles added each year
year_added
2008       2
2009       2
2010       1
2011      13
2012       3
2013      10
2014      23
2015      73
2016     418
2017    1164
2018    1625
2019    1999
2020    1878
2021    1498
Name: count, dtype: int64

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 3
Top 10 Producing Countries
country
United States     3643
India             1045
Unknown            827
United Kingdom     787
Canada             432
France             389
Japan              314
Spain              228
South Korea        226
Germany            225
Name: count, dtype: int64

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 4
Top 5 Most Common Genres
listed_in
International Movies      2752
Dramas                    2427
Comedies                  1674
International TV Shows    1328
Documentaries              869
Name: count, dtype: int64

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 5
Rating Distribution
rating
TV-MA        3183
TV-14        2133
TV-PG         838
R             799
PG-13         490
TV-Y7         330
TV-Y          300
PG            287
TV-G          212
NR             78
G              41
TV-Y7-FV        5
Not Rated       4
NC-17           3
UR              3
66 min          1
74 min          1
84 min          1
Name: count, dtype: int64

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 6
Oldest and Newest Release Years

Oldest release year: 1925
Newest release year: 2021

Titles from the oldest release year:

                                  title     type  release_year
4250  Pioneers: First Women Filmmakers*  TV Show          1925

Titles from the newest release year:

                                  title     type  release_year
1                         Blood & Water  TV Show          2021
2                             Ganglands  TV Show          2021
3                 Jailbirds New Orleans  TV Show          2021
4                          Kota Factory  TV Show          2021
5                         Midnight Mass  TV Show          2021
6      My Little Pony: A New Generation    Movie          2021
8         The Great British Baking Show  TV Show          2021
9                          The Starling    Movie          2021
10  Vendetta: Truth, Lies and The Mafia  TV Show          2021
11                     Bangkok Breaking  TV Show          2021

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 7
Enter a keyword to search in titles: 8

Titles containing "8":
Total matches: 33

,show_id,type,title,release_year,rating,country
479,s480,Movie,Fear Street Part 2: 1978,2021,R,Unknown
489,s490,Movie,Back to Q82,2017,TV-14,"Kuwait, United States"
556,s557,Movie,The 8th Night,2021,TV-14,South Korea
858,s859,Movie,678,2009,TV-14,Unknown
1276,s1277,Movie,M8 - When Death Rescues Life,2019,TV-MA,Unknown
1586,s1587,TV Show,Room 2806: The Accusation,2020,TV-MA,France
2103,s2104,Movie,Class of '83,2020,TV-14,India
2550,s2551,Movie,18 Presents,2020,TV-MA,Italy
2619,s2620,Movie,Lembi 8 Giga,2010,TV-MA,Unknown
2690,s2691,Movie,Code 8,2019,TV-MA,Canada
2917,s2918,TV Show,Taj Mahal 1989,2020,TV-MA,India
3071,s3072,TV Show,Reply 1988,2015,TV-14,South Korea
3587,s3588,TV Show,Victim Number 8,2018,TV-MA,Spain
3712,s3713,Movie,Hikaru Utada Laughter in the Dark Tour 2018,2018,TV-PG,Japan
4052,s4053,Movie,BNK48: Girls Don't Cry,2018,TV-14,Thailand
4350,s4351,TV Show,1983,2018,TV-MA,"Poland, United States"
5115,s5116,Movie,48 Christmas Wishes,2017,TV-G,Canada
5182,s5183,Movie,Let It Fall: Los Angeles 1982-1992,2017,TV-MA,United States
5198,s5199,Movie,SPF-18,2017,PG-13,United States
5433,s5434,TV Show,28 Moons,2016,TV-PG,South Korea

Only the first 20 results are displayed.

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 8
Enter the year content was added: 2007
No content was added in 2007.

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 9
Total Unique Countries
Total unique countries: 124

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 10
Release Year Summary Statistics
Mean: 2014.20
Median: 2017.00
Minimum: 1925
Maximum: 2021
Standard deviation: 8.83
Variance: 77.89

==================================================
        NETFLIX CONTENT EXPLORER
==================================================
1. Count of Movies vs TV Shows
2. Number of titles added each year
3. Top 10 producing countries
4. Top 5 most common genres
5. Rating distribution
6. Oldest and newest release years
7. Search titles by keyword
8. Content added in a specific year
9. Total unique countries
10. Summary statistics on release year
0. Quit
==================================================
Enter your choice (0-10): 0
Thank you for using Netflix Content Explorer.

In [43]:
# Collect exact values for the final project insights

movie_tv_counts = cleaned_df["type"].value_counts()

countries = cleaned_df["country"].str.split(",").explode().str.strip()
top_country = countries.value_counts().index[0]
top_country_count = countries.value_counts().iloc[0]

genres = cleaned_df["listed_in"].str.split(",").explode().str.strip()
top_genre = genres.value_counts().index[0]
top_genre_count = genres.value_counts().iloc[0]

most_added_year = cleaned_df["year_added"].value_counts().idxmax()
most_added_count = cleaned_df["year_added"].value_counts().max()

oldest_year = cleaned_df["release_year"].min()
newest_year = cleaned_df["release_year"].max()

print("Movies and TV Shows:")
print(movie_tv_counts)

print(f"\nTop producing country: {top_country} ({top_country_count} titles)")
print(f"Top genre: {top_genre} ({top_genre_count} titles)")
print(f"Year with most titles added: {most_added_year} ({most_added_count} titles)")
print(f"Oldest release year: {oldest_year}")
print(f"Newest release year: {newest_year}")

Movies and TV Shows:
type
Movie      6131
TV Show    2578
Name: count, dtype: int64

Top producing country: United States (3643 titles)
Top genre: International Movies (2752 titles)
Year with most titles added: 2019 (1999 titles)
Oldest release year: 1925
Newest release year: 2021

## Key Insights

The Netflix dataset contains **6131 Movies** and **2578 TV Shows**, showing that Movies form the larger part of the catalog. **United States** is the leading producing country with **3643 titles**, indicating its strong contribution to Netflix content. The most common genre is **International Movies** with **2752 titles**. Netflix added the largest number of titles in **2019**, with **1999 titles**, which suggests that this was a major period of catalog expansion.